(* type t = Id.t Vect.t *)
(* val powi : 'a Vect.t -> int -> 'a Vect.t *)
(* val pown : 'a Vect.t -> Vect.coeff -> 'a Vect.t *)
(* val to_list : 'a Vect.t -> ('a * Vect.coeff) list *)
(* val of_list : ('a * Vect.coeff) list -> 'a Vect.t *)
(* val vars : 'a Vect.t -> 'a list *)
(* val unit : 'a -> 'a Vect.t *)
(* val eq : 'a Vect.t -> 'a Vect.t -> bool *)
(* val size : 'a Vect.t -> int *)
(* val coeff : 'a Vect.t -> 'a -> Vect.coeff *)
(* val remove : 'a Vect.t -> 'a -> 'a Vect.t *)
(* val scalar : Vect.coeff -> 'a Vect.t -> 'a Vect.t *)
(* val inv : 'a Vect.t -> 'a Vect.t *)
(* val add : 'a Vect.t -> 'a Vect.t -> 'a Vect.t *)
(* val sub : 'a Vect.t -> 'a Vect.t -> 'a Vect.t *)
(* val subst : 'a Vect.t -> 'a -> 'a Vect.t -> 'a Vect.t *)
(* val pp : ?logarithm:bool -> Format.formatter -> Id.t Vect.t -> unit *)
